#!/bin/sh
pushd /Users/ylyan/github/Wordbook/EndToEnd/extract-from-hanvon
cp /Volumes/Untitled\ 1/newword/newword.txt ./hanvon_newword.txt
cp /Volumes/Untitled/newword/newword.txt ./hanvon_newword.txt
# enca -L chinese hanvon_newword.txt
iconv --from-code UCS-2 --to-code=UTF-8 hanvon_newword.txt > newword.txt
/usr/local/bin/python3 ./parsefile_hanvon.py
cp output.txt ../SortedWordbook.txt
popd
pushd /Users/ylyan/github/Wordbook/EndToEnd/
java -jar wordbook.jar
popd
